### ISSUE TITLE
StackedTabNetRegressor 

### ISSUE THREAD

**Issue by pfistfl** [titu1994/tf-TabNet#17]
https://github.com/titu1994/tf-TabNet/blob/9a766711fc8933b1b557019ff09e2e55cea5a4c0/tabnet/stacked_tabnet.py#L351

shouldn't this be `self.stacked_tabnet` like in the classifier? 
I am getting an error that indicates this.
`AttributeError: 'StackedTabNetRegressor' object has no attribute 'tabnet'`

**Comment by atamazian** [comment]
This issue is fixed and should be closed.
