### ISSUE TITLE
Wrong normalization selection?

### ISSUE THREAD

**Issue by jprafael** [titu1994/tf-TabNet#2]
Isn't the logic reversed here?

https://github.com/titu1994/tf-TabNet/blob/ebf8c43b0cfa9b3b778b276a87f73e2e5a5c62dd/tabnet.py#L161

https://github.com/titu1994/tf-TabNet/blob/ebf8c43b0cfa9b3b778b276a87f73e2e5a5c62dd/tabnet.py#L23

**Comment by titu1994** [comment]
Yup you're right. Will fix asap. Find and replace mistake.

**Comment by titu1994** [comment]
Fixed and closed via e149043da1cfea4c3daf1b3fe17a631c2b06090a
