### ISSUE TITLE
Minor error in documentation

### ISSUE THREAD

**Issue by FedericoV** [titu1994/tf-TabNet#3]
https://github.com/titu1994/tf-TabNet/blob/66fa3da7ec916e50899d964b44deeca15e50c633/tabnet/tabnet.py#L97

and

https://github.com/titu1994/tf-TabNet/blob/66fa3da7ec916e50899d964b44deeca15e50c633/tabnet/tabnet.py#L141

Pretty sure both of those should be ['group', 'batch'] :)

**Comment by titu1994** [comment]
Thanks for noticing that! Fixed via 1a9b3c41f60777ae2e3966581cbfee73f6ea867c
