### ISSUE TITLE
v0.1.4 TypeError: 'module' object is not iterable

### ISSUE THREAD

**Issue by JackyP** [titu1994/tf-TabNet#4]
Hello! When I pip install the latest version, I cannot import the module:
```
>>> import tabnet
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Jacky/anaconda3/lib/python3.7/site-packages/tabnet/__init__.py", line 15, in <module>
    __all__ = [*tabnets, *stacked_tabnet]
TypeError: 'module' object is not iterable
```

The issue does not occur if I use 0.1.3.

**Comment by titu1994** [comment]
Thanks for raising this issue. Seems I misspelled the `stacked_tabnets` list with the `stacked_tabnet` module. This has been fixed in v0.4.1 on PyPi which I just pushed.
