### ISSUE TITLE
Question / Feature request: Mixed categorical and numeric columns

### ISSUE THREAD

**Issue by JackyP** [titu1994/tf-TabNet#5]
Many of my datasets have mixed numeric and categorical variables. 

I've read https://github.com/titu1994/tf-TabNet/blob/master/examples/train_embedding.py but I remain a little confused as to how best to implement.

What are the key requirements to make it work? Can the functional API work with it? Would be keen for any advice or functionality that can be built in for this.

Thanks!

**Comment by titu1994** [comment]
You can pass any number of tf.feature_column as a list to tf.keras.DenseFeatures layer. In the above script I've passed a list of just 1 value, you can mix categorical and numeric values in that list. 

After that, simply follow the rest of the steps and treat it as the same, there should be no code changes required.
