### ISSUE TITLE
Feature transformer is all decision-step independent transformer blocks

### ISSUE THREAD

**Issue by zmjjmz** [titu1994/tf-TabNet#7]
Hey there,

I think there's a mistake in the feature transformer implementation here (i.e., Fig. b) compared to the original implementation. My understanding based on the paper and the original is that Transforms 3 & 4 should be dependent on the decision step (i.e., the weights should not be shared between the decision steps), whereas Transforms 1 & 2 should be the same weights for each decision step.

Note that this is implemented in the original model by having the (I think now deprecated) `tf.layers` [`reuse`](https://github.com/google-research/google-research/blob/master/tabnet/tabnet_model.py#L134) flag set for the first two, and for the rest to have [different names](https://github.com/google-research/google-research/blob/master/tabnet/tabnet_model.py#L147) based on the decision step.

If I'm understanding this code correctly (and I might not be), there are only 4 instances of the `TransformBlock` model, and there's no difference in how these are instantiated or called between blocks 1&2 and blocks 3&4. I'm fairly certain this means that they're all shared weights between decision steps, which does not match the model detailed in the paper.

A possible solution would be to make two lists (3&4) of `num_decision_steps` `TransformBlock` instances and reference the appropriate `TransformBlock` in the [call](https://github.com/titu1994/tf-TabNet/blob/master/tabnet/tabnet.py#L217) method, i.e.

I think this would be a fairly simple change:

In `__init__`
```
self.transform_f3_list = [TransformBlock(2 * self.feature_dim, self.batch_momentum,       
   self.virtual_batch_size, self.num_groups) for _ in range(self.num_decision_steps)]
```
and then in `call`
```
transform_f3 = self.transform_f3_list[ni](transform_f2, training=training)
transform_f3 = (glu(transform_f3, self.feature_dim) +
                          transform_f2) * tf.math.sqrt(0.5)
```

Let me know what you think! I may go ahead and try this myself and submit a PR if it's appropriate.

**Comment by titu1994** [comment]
You are right, I seem to have missed the reuse flag in TF 1.x. The above steps you mentioned are correct and need to be repeated verbatim for `f4` blocks as well since they are also not reused.  Please submit a PR at your convenience, ill review it asap.

**Comment by zmjjmz** [comment]
I swear I'll do this PR tonight, but I also noticed that similarly the [`transform_coef`](https://github.com/titu1994/tf-TabNet/blob/master/tabnet/tabnet.py#L243) is sharing weights between decision steps, which I thought was correct (the paper is less clear on this) but then reading the original [implementation](https://github.com/google-research/google-research/blob/master/tabnet/tabnet_model.py#L190) it seems like there's a similar issue. I've made and used a `transform_coef_list` and saw no real difference on the Iris example.

**Comment by titu1994** [comment]
Hmm let's remain consistent with the original implementation and make it a list as well.
